version: '3.0'

services:

  web:
    container_name: web
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/usr/src/app'
    ports:
      - '4000:4000'
    environment:
      - NODE_ENV=production
    links:
      - redis

  redis:
    container_name: redis
    hostname: redis
    image: redis

  redisCommander:
    container_name: redis-commander
    image: tenstartups/redis-commander
    command: --redis-host redis
    links:
      - redis:redis
    ports:
      - "8081:8081"

  webserver:
    container_name: webserver
    image: nginx
    volumes:
     - ./nginx/mysite.template:/etc/nginx/conf.d/mysite.template
    ports:
     - '3000:3000'
    command: /bin/bash -c "envsubst '' < /etc/nginx/conf.d/mysite.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
