version: '3.3'

services:

  webapp:
    container_name: webapp
    depends_on:
     - redis
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/usr/src/app'
      - 'usr/src/app/node_modules'
    ports:
      - '4000:4000'
    environment:
      - NODE_ENV=production
    hostname: webapp

  redis:
    container_name: redis
    hostname: redis
    image: redis

  redisCommander:
    container_name: redis-commander
    depends_on:
     - redis
    image: tenstartups/redis-commander
    command: --redis-host redis
    ports:
      - "8081:8081"

  webserver:
    container_name: webserver
    depends_on:
     - webapp
    image: nginx
    volumes:
     - ./nginx/mysite.template:/etc/nginx/conf.d/mysite.template
    ports:
     - '80:80'
    environment:
     - APP_HOST=webapp
     - APP_PORT=4000
    command: /bin/bash -c "envsubst '$$APP_HOST, $$APP_PORT' < /etc/nginx/conf.d/mysite.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
